# Generated by Django 5.2.12 on 2026-03-25 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('academic_year', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DROPPED', 'Dropped'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.subject')),
            ],
            options={
                'unique_together': {('student_id', 'course_id', 'academic_year', 'semester')},
            },
        ),
    ]
