# Generated by Django 5.2.12 on 2026-03-25 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('CSE', 'Cse'), ('ECE', 'Ece'), ('ME', 'Me'), ('CE', 'Ce'), ('EE', 'Ee')], max_length=50)),
                ('semester', models.IntegerField()),
                ('credits', models.IntegerField(default=0)),
                ('theory_marks', models.IntegerField(default=100)),
                ('practical_marks', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['branch', 'semester'], name='courses_sub_branch_46abd5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
                ('academic_year', models.IntegerField()),
                ('total_classes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.facultypersonal')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.subject')),
            ],
        ),
    ]
