# Generated by Django 5.2.12 on 2026-03-25 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('theory_marks', models.IntegerField(default=0)),
                ('practical_marks', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('grade', models.CharField(choices=[('A+', 'A Plus'), ('A', 'A'), ('B+', 'B Plus'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='C', max_length=5)),
                ('semester', models.IntegerField()),
                ('academic_year', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='courses.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='accounts.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='courses.subject')),
            ],
            options={
                'unique_together': {('student_id', 'subject_id', 'course_id', 'semester', 'academic_year')},
            },
        ),
    ]
